HOST: http://www.google.com/

--- Wheelspecs API v1 ---
---
Welcome to the documentation for the Wheelspecs API. 
---

--
Wheel resources
The following is a section of resources related to wheels
--
List products added into your shopping-cart. (comment block again in Markdown)
GET /wheels
< 200
< Content-Type: application/json
{ "items": [
  {  
    "id": "425",
    "brandId": "140",
    "brand": "Volk Racing", 
    "model":"TE-37", 
    "status": "current"", 
    "manufacturingMethod": "Forged", 
    "images": [
        {
            "url": "/Images/WheelModels/volk_te37limited.png",
            "url": "/Images/WheelModels/volk_te37magnesium.png"
        }    
    ],
    "links": [
        {
            "type": "self", "url": "/Volk-Racing-TE37_wm425.aspx"
            "type": "parent", "url": "/Volk-Racing_wb140.aspx"
        }
    ]
  }
]}

Save new products in your shopping cart
POST /wheels
> Content-Type: application/json
{  
"brandId": "140",
"brand": "Volk Racing", 
"model":"TE-37", 
"status": "current"", 
"manufacturingMethod": "Forged", 
"images": [
    {
        "url": "/Images/WheelModels/volk_te37limited.png",
        "url": "/Images/WheelModels/volk_te37magnesium.png"
    }    
]
}
< 201
< Location: "/Volk-Racing-TE37_wm425.aspx"